# Generated by Django 3.1.7 on 2021-03-01 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210301_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.vote'),
        ),
    ]
